---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "docker"
        state: "present"
    - name: Start Docker server
      service:
        name: docker
        state: started
        enabled: True
...
